image: node:16

pipelines:
  branches:
    dev:
      - parallel:
          - step:
              name: Build and Test App
              caches:
                - node
              script:
                - export REACT_APP_API_BASE_URL=$API_BASE_URL_DEV
                - export REACT_APP_USER_POOL_ID=$USER_POOL_ID_DEV
                - export REACT_APP_USER_POOL_WEB_CLIENT_ID=$USER_POOL_WEB_CLIENT_ID_DEV
                - yarn
                - yarn build
              artifacts:
                - build/**
          - step:
              name: Security Scan
              script:
                # Run a security scan for sensitive data.
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Dev Environment
          deployment: Development
          clone:
            enabled: false
          script:
            # Sync your files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: $BUCKET_NAME
                LOCAL_PATH: build
            # Triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                DISTRIBUTION_ID: $DISTRIBUTION_ID
    test:
      - parallel:
          - step:
              name: Build and Test App
              caches:
                - node
              script:
                - export REACT_APP_API_BASE_URL=$API_BASE_URL_TEST
                - export REACT_APP_USER_POOL_ID=$USER_POOL_ID_TEST
                - export REACT_APP_USER_POOL_WEB_CLIENT_ID=$USER_POOL_WEB_CLIENT_ID_TEST
                - yarn
                - yarn build
              artifacts:
                - build/**
          - step:
              name: Security Scan
              script:
                # Run a security scan for sensitive data.
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Test Environment
          deployment: Test
          clone:
            enabled: false
          script:
            # Sync your files to S3
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: $BUCKET_NAME
                LOCAL_PATH: build
            # Triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                DISTRIBUTION_ID: $DISTRIBUTION_ID
